"""Phase 5: Data Preparation — decompress local and fetch remote data.

After provisioning (hf-ops + hf-run + nfs-data), this phase:
- Splits requested chromosomes into local (chr1-10 in data container)
  and remote (chr11+ via tabix/curl download)
- Decompresses local VCF/annotation files from /work_dir/20130502/ to /work_dir/
- For remote chromosomes, creates a K8s Job to download VCF files via
  Composer-generated commands (tabix for regions, curl|gunzip for full chroms)
- Scans all VCF files for exact row counts
- Populates state.chromosome_data for workflow generation
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from workflow_conductor.k8s import Kubectl
from workflow_conductor.models import (
    ChromosomeData,
    PipelinePhase,
    PipelineState,
)
from workflow_conductor.ui.display import display_phase_header

if TYPE_CHECKING:
    from workflow_conductor.config import ConductorSettings

logger = logging.getLogger(__name__)


def _filter_commands_for_chromosomes(
    commands: list[str], chromosomes: list[str]
) -> list[str]:
    """Filter download commands to only include specified chromosomes."""
    filtered = []
    for cmd in commands:
        for chrom in chromosomes:
            if f"chr{chrom}." in cmd or f"chr{chrom} " in cmd:
                filtered.append(cmd)
                break
    return filtered


def _build_tabix_job(commands: list[str], namespace: str, image: str) -> dict[str, Any]:
    """Build K8s Job manifest for remote VCF extraction."""
    script = " && ".join(commands)
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": "tabix-extract",
            "namespace": namespace,
        },
        "spec": {
            "backoffLimit": 0,
            "template": {
                "metadata": {
                    "labels": {"app": "hyperflow", "role": "tabix-extract"},
                },
                "spec": {
                    "restartPolicy": "Never",
                    "containers": [
                        {
                            "name": "tabix",
                            "image": image,
                            "workingDir": "/work_dir",
                            "command": ["/bin/sh", "-c", script],
                            "volumeMounts": [
                                {
                                    "name": "workflow-data",
                                    "mountPath": "/work_dir",
                                },
                            ],
                            "resources": {
                                "requests": {"cpu": "500m", "memory": "512Mi"},
                            },
                        }
                    ],
                    "volumes": [
                        {
                            "name": "workflow-data",
                            "persistentVolumeClaim": {"claimName": "nfs"},
                        }
                    ],
                },
            },
        },
    }


async def run_data_preparation_phase(
    state: PipelineState,
    settings: ConductorSettings,
) -> PipelineState:
    """Decompress data files, scan row counts, populate chromosome_data.

    Requires state.engine_pod_name and state.namespace from provisioning.
    The nfs-data job has already staged compressed files to /work_dir/20130502/.

    For chromosomes not in the data container (chr11+), runs a K8s Job
    with the gatk image to download VCF files via tabix or curl commands
    generated by the Workflow Composer.
    """
    display_phase_header(PipelinePhase.DATA_PREPARATION)

    if not state.engine_pod_name:
        raise ValueError(
            "Cannot prepare data: engine pod not set (provisioning phase required)"
        )
    if not state.namespace:
        raise ValueError(
            "Cannot prepare data: namespace not set (provisioning phase required)"
        )

    kubectl = Kubectl(kubeconfig=settings.kubernetes.kubeconfig)
    namespace = state.namespace

    # Step 1: Determine needed chromosomes from workflow plan
    chromosomes = state.workflow_plan.chromosomes if state.workflow_plan else []
    if not chromosomes:
        raise ValueError("No chromosomes specified in workflow plan")

    # Step 2: Split into local (data container) and remote (need download)
    local_chroms = [c for c in chromosomes if c in settings.data_container_chromosomes]
    remote_chroms = [
        c for c in chromosomes if c not in settings.data_container_chromosomes
    ]

    logger.info(
        "Preparing data: %d local, %d remote chromosomes",
        len(local_chroms),
        len(remote_chroms),
    )

    # Step 3: Stage shared files (columns.txt, population lists) and
    # decompress local VCF files (chr1-10 from data container)
    stage_shared = (
        "cp /work_dir/20130502/columns.txt /work_dir/ 2>/dev/null || true && "
        "cp /work_dir/populations/* /work_dir/ 2>/dev/null || true"
    )
    if local_chroms:
        logger.info(
            "Step 1: Decompressing local data for chr%s",
            ",".join(local_chroms),
        )
        chrom_globs = " ".join(f"ALL.chr{c}.*.vcf.gz" for c in local_chroms)
        decompress_cmd = (
            "cd /work_dir/20130502 && "
            f"for f in {chrom_globs}; do "
            '  gunzip -c "$f" > "/work_dir/$(basename $f .gz)" ; '
            f"done && {stage_shared}"
        )
    else:
        decompress_cmd = stage_shared

    await kubectl.exec_in_pod(
        state.engine_pod_name,
        ["/bin/sh", "-c", decompress_cmd],
        namespace=namespace,
        container="hyperflow",
        timeout=600,
    )

    # Step 4: Download remote data files via K8s Job
    if remote_chroms:
        download_commands = (
            state.workflow_plan.download_commands if state.workflow_plan else []
        )
        if not download_commands:
            raise ValueError(
                f"Chromosomes {remote_chroms} require remote extraction but "
                "no download commands available from workflow planner."
            )

        remote_commands = _filter_commands_for_chromosomes(
            download_commands, remote_chroms
        )
        if not remote_commands:
            raise ValueError(
                f"No download commands found for chromosomes {remote_chroms}"
            )

        logger.info(
            "Step 2: Downloading remote data for chr%s (%d commands)",
            ",".join(remote_chroms),
            len(remote_commands),
        )
        job_manifest = _build_tabix_job(
            commands=remote_commands,
            namespace=namespace,
            image=settings.tabix_image,
        )
        await kubectl.apply_json(job_manifest, namespace=namespace)
        await kubectl.wait_for_job(
            "tabix-extract",
            namespace=namespace,
            timeout=settings.tabix_job_timeout,
        )

    # Step 5: Discover VCF files and scan for exact row counts.
    # File naming varies by Composer version (e.g. ALL.chr17.250000.vcf vs
    # ALL.chr17.brca1.vcf), so we discover them dynamically.
    logger.info("Step 3: Scanning VCF files for row counts")
    discover_cmd = (
        "for c in " + " ".join(chromosomes) + "; do "
        "  vcf=$(ls /work_dir/ALL.chr${c}.*.vcf 2>/dev/null "
        "    | grep -v annotation | grep -v sites | head -1); "
        "  ann=$(ls /work_dir/ALL.chr${c}.*annotation*.vcf 2>/dev/null | head -1); "
        '  if [ -n "$vcf" ]; then '
        '    count=$(grep -c -v "^#" "$vcf"); '
        '    echo "${c}:${count}:$(basename $vcf):$(basename ${ann:-none})"; '
        "  fi; "
        "done"
    )
    output = await kubectl.exec_in_pod(
        state.engine_pod_name,
        ["/bin/sh", "-c", discover_cmd],
        namespace=namespace,
        container="hyperflow",
        timeout=300,
    )

    # Step 6: Parse output → chromosome_data
    # Format: "17:1234:ALL.chr17.brca1.vcf:ALL.chr17.brca1.annotation.vcf"
    state.chromosome_data = []
    for line in output.strip().splitlines():
        parts = line.split(":")
        if len(parts) < 3:
            continue
        chrom = parts[0].strip()
        count_str = parts[1].strip()
        vcf_file = parts[2].strip()
        ann_file = parts[3].strip() if len(parts) > 3 and parts[3] != "none" else ""
        try:
            row_count = int(count_str)
        except ValueError:
            logger.warning("Could not parse row count for chr%s: %s", chrom, count_str)
            continue

        state.chromosome_data.append(
            ChromosomeData(
                chromosome=chrom,
                vcf_file=vcf_file,
                row_count=row_count,
                annotation_file=ann_file,
            )
        )
        logger.info("  chr%s: %d variants (%s)", chrom, row_count, vcf_file)

    if not state.chromosome_data:
        raise ValueError("No chromosome data could be scanned from VCF files")

    logger.info(
        "Data preparation complete: %d chromosomes ready",
        len(state.chromosome_data),
    )
    return state
